config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes, only: [:index, :show]
end

app/models/chef.rb
class Chef < ContentfulModel::Base
  self.content_type_id = "chef"

  coerce_field name: :String
end

app/models/recipe.rb
class Recipe < ContentfulModel::Base
  self.content_type_id = "recipe"

  has_many :tags
  has_one :chef

  coerce_field title: :String
  coerce_field description: :String
end

app/models/tag.rb
class Tag < ContentfulModel::Base
  self.content_type_id = "tag"

  coerce_field name: :String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = decorated_recipes
  end

  def show
    @recipe = decorated_recipe

    return not_found if @recipe.object.nil?

    set_recipe_meta_title
  end

  private

  def decorated_recipes
    RecipeDecorator.decorate_collection(recipes)
  end

  def decorated_recipe
    RecipeDecorator.decorate(recipe)
  end

  def recipes
    Recipe.all.load
  end

  def recipe
    Recipe.find(params[:id])
  end

  def set_recipe_meta_title
    set_meta_tags(title: @recipe.title)
  end

  def not_found
    render file: Rails.root.join("public/404"), status: :not_found, layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def parse_markdown(markdown_string)
    renderer = Redcarpet::Render::HTML
    markdown = Redcarpet::Markdown.new(renderer)

    markdown.render(markdown_string).html_safe
  end
end

app/views/layouts/_header.html.erb
<header class="header">
  <%= link_to root_path do %>
    <h1><%= I18n.t("title") %></h1>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= locale %>">
  <head>
    <%= display_meta_tags site: I18n.t("title"), 
                          description: I18n.t("description"), 
                          keywords: I18n.t("keywords") %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1"> 
  </head>

  <body>
    <%= render "layouts/header"%>

    <main class="content-container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_recipe_preview.erb
<div class="recipe-preview">
  <%= link_to recipe_path(recipe.id) do %>
    <%= image_tag recipe.preview_photo_src, size: "300x200", alt: recipe.title %>

    <div class="recipe-preview__content">
      <%= recipe.title %>
    </div>
  <% end %>
</div>

app/views/recipes/_tag.html.erb
<span class="recipe__tag">
  <%= tag.name %>
</span>

app/views/recipes/index.html.erb
<h2><%= I18n.t("recipes.all_recipes") %></h2>

<div class="recipes">
  <%= render partial: "recipe_preview", collection: @recipes, as: :recipe, cached: true %>
</div>

app/views/recipes/show.html.erb
<% cache @recipe do %>
  <article class="recipe">
    <h2><%= @recipe.title %></h2>

    <p>
      <%= link_to I18n.t("recipes.back_to_overview"), recipes_path %>
    </p>

    <%= image_tag @recipe.photo_src, class: "recipe__image", alt: @recipe.title %>
    
    <p>
      <%= render partial: "tag", collection: @recipe.tags, cached: true %>
    </p>

    <p>
      <% if @recipe.has_chef? %>
        <b><%= I18n.t("recipes.chef") %>: <%= @recipe.chef_name %></b>
      <% end %>
    </p>

    <%= @recipe.decription_html %>
  </article>
<% end %>